services:
  mysql:
    image: mysql:latest
    container_name: contenedor
    restart: always
    environment:
        MYSQL_DATABASE: basededatos
        
        MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3308:3306
    volumes:
      - miVolumen_mysql_data:/var/lib/mysql

volumes:
    miVolumen_mysql_data: